### ISSUE TITLE
Understanding the groups parameter in escape

### ISSUE THREAD

**Issue by dylanmr** [ncborcherding/escape#10]
Hi Nick, 

Thanks for the great tool. I was looking through the code you have for escape to better understand how the groups parameter works in the enrichIT function. If I understand it correctly  you are splitting the data into n number of groups of cells and then plugging these groups of cells into GSVA. My question is, since GSVA calculates a distribution for each gene, and a rank for that gene based on the inferred distribution, would this not be an issue when generating the gene rankings if you have split the cells into multiple groups? I may be over thinking this, but I was just curious to hear what you thought. 

Best, 
Dylan

**Comment by ncborcherding** [comment]
Hey Dylan,

Good questions and probably bears the need to clarify in the documentation. So thanks I will add some in the next commit.

**Short answer:** `enrichIt()` is calculating enrichment scores using single-sample GSEA, which means gene expression across each sample (single-cell) is being calculated instead of the traditional grouped version of GSEA. So breaking into groups does not matter - more of a saving of RAM approach.

**More Specific** 
If you look deep into the `enrichIt()` function, you will see the following after the group break down:

```
#cnts[,i:last] is the the group
#egc is the gene set information
a <- suppressWarnings(gsva(cnts[,i:last], egc, method = 'ssgsea', 
            ssgsea.norm = TRUE, kcdf = "Poisson", parallel.sz = cores, 
            BPPARAM = SnowParam()))
```
I show this to say that each enrichment calculation is based on the distribution/ranking of gene expression in each single-cell via the **method = 'ssgsea'** and the enrichment score is calculated, there is a normalizing function **ssgsea.norm = TRUE** to return the final enrichment score per cell. This normalized enrichment score is the same idea as the output behind traditional GSEA and allows for the comparison between groups. 

Let me know if that helps and feel free to let me know if you have any more questions or suggestions for the package.

Thanks,
Nick

**Comment by dylanmr** [comment]
Hi Nick , 

Thanks for the clarification. I guess more along the lines of what I was thinking can be seen here in the GSVA vignette pdf: 

![image](https://user-images.githubusercontent.com/12213489/100246434-6b9c9f80-2f39-11eb-9d02-cc496d8e853a.png)

So if you wanted to rank gene X, you would look at the distribution of gene X across the entire dataset, construct the distribution of gene X, and then assign gene X a rank statistic based on where its expression level is along the cdf. 

I guess I was just wondering how splitting the dataset into groups of cells (each group which may be represented by an unbalanced group of cells) would impact how that distribution is constructed, and could then impact the rank statistic each gene receives. 

Best, 
Dylan

**Comment by ncborcherding** [comment]
Hey Dylan,

I see what you are saying now - because the rank statistic and then subsequent enrichment score is calculated per single-cell, `enrichIt()` is not comparing the rank gene X across groups. Although using the GSVA package, the calculation is using ssGSEA - check out [pg 5](https://www.bioconductor.org/packages/release/bioc/vignettes/GSVA/inst/doc/GSVA.pdf) of the GSVA manual at the very bottom.

<img width="612" alt="Screen Shot 2020-11-25 at 9 34 38 AM" src="https://user-images.githubusercontent.com/22754118/100248758-7b988d00-2f01-11eb-8043-07180ad8f8c8.png">

As opposed to GSVA, ssGSEA is producing an enrichment score for each cell regardless of group identity (based on the expression distribution of the genes in that cell), which then allows for the assignment of groups (after the enrichment) and subsequent downstream analysis. **So having the calculation broken down into groups of 1000 cells does not affect the analyses because there is no ranking of genes across groups to yield the normalized enrichment scores.**

Underlying reason for not using `method = "gsva"`

In terms of reasoning for this - I tried various approaches to gene set enrichment analyses for single-cells and this was by far the easiest to scale. I think GSVA would work well for a small number of single-cells, but used exponentially more time and resources as data sets got larger (I think this is due to the ranking portion of the workflow). ssGSEA on the other hand is **1)** more self-contained and should blunt drop out effect **2)** can be broken up (not by groups) to save on memory and **3**) gives an enrichment score that is comparable across multiple groups - say if you wanted to compare the difference between clusters, time points and tissues - this can be done with just the single `enrichIt()` output. 

Hope that helps better explain why you do not need to think about grouping as you run enrichIt(). Let me know if you have anymore questions.

Thanks,
Nick

**Comment by dylanmr** [comment]
Thats perfect. I hadn't fully understood the difference between ssGSEA and GSVA. Thanks so much for your time in explaining this. 

Dylan
