### ISSUE TITLE
Using normalised vs normalised values 

### ISSUE THREAD

**Issue by Shubhra1994** [ncborcherding/escape#102]
Hello, 
Great package, thank you.
I have a doubt about using the normalization function within the escape.matrix function v/s using the  performNormalization function by itself.
If I am correct, the  performNormalization() is set to false by default and the tutorial does not set it otherwise and the downstream analysis, the visualisations are done on the non normalised slots as well.

What do you recommend:
-running the escape.matrix() followed by performNormalization() and viz. on non-normalised slot. 
-running the escape.matrix() with normalisation set to true followed by viz. on non-normalised slot. 

Best

**Comment by ncborcherding** [comment]
@Shubhra1994 

Thanks for reaching out - you are correct, the vignette and ```escape.matrix()``` do not use normalization as a default. This was due to the consideration for computational efficiency (the default normalization can take a lot of time) and I wanted to allow users to have the option to incorporate other normalizations if they choose. 

If you are looking to normalize your data, I would compare the non-normalized values and the normalized values. The assumption in normalization is that the level of counts per cell influence the enrichment value. You can visualize either normalized for non-normalized values, I visualized non-normalized in the vignette for the above reasons. 

Nick
