### ISSUE TITLE
batch effects

### ISSUE THREAD

**Issue by Flu09** [ncborcherding/escape#124]
Hello, I am interested in this great tool. what I understand is that methods that use aucell and ssgsea scores are less affected by batch effects than other methods,  for example MAST where we have to specify latent variables.

  I already have a seurat object  normalized and scaled ( NormalizeData() and ScaleData()  for all genes) and the object contains data from different studies. So I want to make sure that what I understand is correct and this tool is suitable for such case.

**Comment by ncborcherding** [comment]
Hey @Flu09, 

I am not sure if any of the enrichment methods are better in the context of batch effects. I avoid using aucell because it is not deterministic - meaning you will get different results running the aucell enrichment calculation twice. 

All method take the raw counts as input, so you do not need to normalized or scale. But you should check the output of ```runEscape()``` or ```escape.matrix()``` to quantify any batch effect. MAST could be applied in order to specify latent variables. 

Hope that helps and let me know if you have any other questions.
Nick

**Comment by Flu09** [comment]
Thank you.How to check the output of runEscape() or escape.matrix() to quantify any batch effect? 

You mean that MAST can be applied on the ES scores after runEscape() and performNormalization() steps?
