### ISSUE TITLE
what's the means of "group" in enrichIt function ?

### ISSUE THREAD

**Issue by zqyhyunbin** [ncborcherding/escape#19]
Thanks for the useful package. And i am using it on my own data, but a little confused what's the "group" means ? I notice the
reminder "**Using sets of 1000 cells. Running 2 times**" when i run it by default, but the raw data contain more than 1000 cells, should i set to the real cell number?

**Comment by ncborcherding** [comment]
Hey zqyhyunbin,

The group refers to number of cells that are run at one time

> "Using sets of 1000 cells. Running 2 times"

This means that there are > 1000 cells and the GSEA process will run twice in order to produce the output for 1000+ cells. 

For data sets that are smaller like 2 - 10,000 cells, this is not really an issue. However, running ```enrichIt()``` with a large data set can be particularly inconvenient in terms of computation demands unless you break the samples up. This ultimately does not effect the enrichment scores, as we are running ssGSEA.

Hope that answers the question and let me know if you have any other questions.

Thanks,
Nick
