### ISSUE TITLE
NES comparison between cells

### ISSUE THREAD

**Issue by Jeron1996** [ncborcherding/escape#23]
Thanks for this great package!

I have a question regarding the comparison of genesets within a cell. I want to use the C8 collection and determine which of those gene sets is the most enriched in a particular cell. 

Currently, I am doing a z-transformation on the EnrichIT output for each gene set and then determine which gene set has the highest z-score within a particular cell. Could you comment on this approach and perhaps advise on a more streamlined method?

Best,

Jeron

**Comment by ncborcherding** [comment]
Hey Jeron,

Thanks for reaching out. 

One issue I have with the approach you describe is comparisons at the level of a single cell. Due to drop-out effect, we expect to have a degree of heterogeneity among enrichment of cells derived from the same origin. When you are thinking about enrichment in single-cell, I would encourage the analysis at multiple cell levels or cluster level when possible. 

So one thing I do is find the median enrichment of gene sets of interest by cluster or other categorical variable (like tissue) and just look at the data as a heatmap. 

Hope that helps, feel free to reach out if you have any more questions!
Nick

**Comment by Jeron1996** [comment]
Hi Nick,

thanks for clearing this up for me. Now I also understand the GSEA approach in your clear cell renal carcinoma paper a lot more.

Cheers,
Jeron
