### ISSUE TITLE
Cannot get vignette to run fully

### ISSUE THREAD

**Issue by NGuslund** [ncborcherding/escape#34]
Hi, thank you for your vignette http://www.bioconductor.org/packages/release/bioc/vignettes/escape/inst/doc/vignette.html

I am trying to understand the analysis so have followed this vignette using the pbmc_small dataset.

After running:
dittoHeatmap(sce, genes = NULL, 
             metas = c("HALLMARK_APOPTOSIS", "HALLMARK_DNA_REPAIR", "HALLMARK_P53_PATHWAY"), 
             annot.by = "groups", 
             fontsize = 7,
             heatmap.colors = colors(50))
             
I get this error: Error: subscript contains invalid names

What I am really interested in is assigning the pathways a significance. When I run this I get the following error:
output <- getSignificance(ES2, group = "cluster", fit = "linear.model")
Error in match.arg(fit, choices = c("T.test", "ANOVA", "Wilcoxon", "LR")) : 
  'arg' should be one of “T.test”, “ANOVA”, “Wilcoxon”, “LR”

When I run this: 
dittoHeatmap(pbmc_small, genes = NULL, metas = names(ES.seurat), 
             annot.by = "groups", 
             fontsize = 7, 
             cluster_cols = TRUE,
             heatmap.colors = colors(50))
It works fine. However, when I run it on my own dataset using the Reactome dataset I get so many pathways that the heatmap is unreadable. Is there a way to only show the most differential pathways across my groups?

Thanks for your time,
Naomi

**Comment by ncborcherding** [comment]
Hey Naomi, 

Thanks for reaching out!

Looks like a couple of things are going on:

> dittoHeatmap(sce, genes = NULL,
metas = c("HALLMARK_APOPTOSIS", "HALLMARK_DNA_REPAIR", "HALLMARK_P53_PATHWAY"),
annot.by = "groups",
fontsize = 7,
heatmap.colors = colors(50))
> I get this error: Error: subscript contains invalid names

This is due to different versions of dittoseq from the Bioconductor. I recommend you visit their [GitHub repo](https://github.com/dtm2451/dittoSeq) and install the newest version using 

`devtools::install_github("dtm2451/dittoSeq")`

> output <- getSignificance(ES2, group = "cluster", fit = "linear.model")
Error in match.arg(fit, choices = c("T.test", "ANOVA", "Wilcoxon", "LR")) :
'arg' should be one of “T.test”, “ANOVA”, “Wilcoxon”, “LR”

This is a difference in the version of escape - you are currently running the dev version (I assume) of escape, which added the Wilcoxon and logistic regression testing. The vignette on bioconductor does not have these, check out the most [up-to-date vignette](https://ncborcherding.github.io/vignettes/escape_vignette.html). As a side note, I had to remove the linear model from the testing options as it was overfitting the data.

> When I run this:
dittoHeatmap(pbmc_small, genes = NULL, metas = names(ES.seurat),
annot.by = "groups",
fontsize = 7,
cluster_cols = TRUE,
heatmap.colors = colors(50))
It works fine. However, when I run it on my own dataset using the Reactome dataset I get so many pathways that the heatmap is unreadable. Is there a way to only show the most differential pathways across my groups?

Yes absolutely, you can run ```getSignificance()``` and indemnity the names of the pathways/gene sets that are significantly altered and then specifically call the names in the ```dittoHeatmap()``` function. 

```
output <- getSignificance(ES2, group = "cluster", fit = "linear.model")
filteredOut <- output[output$FDR < 0.05,]
dittoHeatmap(pbmc_small, genes = NULL, metas = rownames(filteredOut),
annot.by = "groups",
fontsize = 7,
cluster_cols = TRUE,
heatmap.colors = colors(50))
```

Hope that helps and let me know if you have any more questions.

Nick
