### ISSUE TITLE
Absence of method parameter in master branch as compared to the vignette

### ISSUE THREAD

**Issue by matt-sd-watson** [ncborcherding/escape#42]
I noticed that the vignette found here: 
https://ncborcherding.github.io/vignettes/escape_vignette.html

provides function parameters to change the method for GSEA (both UCell and singscore are shown as alternative options).

However in the source code on the mai branch for enrichIt, this parameter is not included. 

The method seems to have this parameter in the dev branch. If this is the case, is this parameter still in a beta state/untested?

**Comment by ncborcherding** [comment]
Hey Matt,

Thanks for reaching out - yes both singscore and UCell alternative approaches are only available in the dev version. Apologies, I should annotate the repo vignette a little better (the vignettes in the versions themselves are correct though - see ```browseVignettes("escape")```). 

They are still technically in beta - I am working on updating everything for bioconductor, so that is when I will commit to master branch. I am planning to drop singscore, after testing I think there are a lot of issues with it compared to UCell or ssGSEA. 

Let me know if you have any other questions.

Nick
