### ISSUE TITLE
Info ES

### ISSUE THREAD

**Issue by NoemieL** [ncborcherding/escape#43]
Hi, 
Thanks for this package! I have a question regarding how you get the ES. I used enrichIt on a SingleCellExperiment object without asking for the normalisation. I get very hight values between 3000 to 5000 for the 3 misigdb that I am interested on. Do you think it is making sens? when I used normalisation I get the values between 0 and 1 like you mension in another post. Then when I used dittoHeatmap the scale is between -4 and 4 in both cases. I was wandering if dittoHeatmap is normalising the data by itself? Also I try to getSignificance but it looks like it needs a seurat object. Is it possible to use it with my SingleCellExperiment object?

Thank you very much in adavnces

**Comment by ncborcherding** [comment]
> get very hight values between 3000 to 5000 for the 3 misigdb that I am interested on. Do you think it is making sens?

Yes this makes sense. The raw enrichment can vary quite a bit depending on the input and individual gene set. The major limitation of the normalization step it makes the data "batch" dependent or dependent on the cells used for the analysis because the range of 0 to 1 is determined by the max and min values seen in the data. 

> Then when I used dittoHeatmap the scale is between -4 and 4 in both cases. I was wandering if dittoHeatmap is normalising the data by itself?

```dittoHeatmap()``` default is to z-score transform the data, so the range -4 to 4 is standard deviations of the data. 

> Also I try to getSignificance but it looks like it needs a seurat object. Is it possible to use it with my SingleCellExperiment object?

Actually, get significant is asking for a data frame of the enrichment values. But making it compatible with single-cell objects is a good suggestion and I will add that to the "to-do" list. 

Please let me know if you have any additional questions or issues. 

Nick

**Comment by NoemieL** [comment]
Thank you very much Nick!
