### ISSUE TITLE
escape.matrix() still producing negative values and Seurat object compatibility

### ISSUE THREAD

**Issue by jdarmitage** [ncborcherding/escape#81]
Hi,

Thanks for this excellent package. I have a few issues related to using the escape.matrix() function.

1. When I run escape.matrix() using make.positive=TRUE I still seem to be encountering negative values when inspecting the escape matrix:

```
enrichment.scores <- escape.matrix(pbmc.subsampled@assays$RNA@counts,
                        gene.sets = GS.H, 
                        min.size = 5,
                        groups = 5000,
                        make.positive = T)

unname(enrichment.scores[1:25,"HALLMARK-APICAL-SURFACE"]) # Check output for negative values

[1]  238.31467   28.20084  516.31585 1613.86336  895.64486  204.01312  722.12098  366.06094  484.61148
[10]  660.86589  -87.00079  284.94365  345.54126  -80.09417  455.47066  634.41814  -79.64764  444.50105
[19]  539.28419  728.13522  517.28865 -554.10712  339.57918  858.37650  224.52932
```

2. My second (unrelated) problem is with using the seurat object directly (as opposed to using the assay matrix above. If I run the below using the seurat object I get the following error:

```
enrichment.scores <- escape.matrix(pbmc.subsampled,
                        gene.sets = GS.H, 
                        min.size = 5,
                        groups = 5000,
                        make.positive = T)

Error in intI(i, n = d[1L], dn[[1L]], give.dn = FALSE) : 
  invalid character indexing
```

Also lastly, will there be multi-core support for this function, like with enrichIt()?

Thanks again.

**Comment by ncborcherding** [comment]
Hey @jdarmitage 

Thanks for reaching out - as escape v2 is still in beta, there are a number of things to track down before it is ready to go, so I appreciate the issues. 

> When I run escape.matrix() using make.positive=TRUE I still seem to be encountering negative values when inspecting the escape matrix:

The **make.positive** argument only gets used if **normalize = TRUE**, so there would not be any adjustments in values. I have updated the documentation in the function to clarify this. 

> Also lastly, will there be multi-core support for this function, like with enrichIt()?

Yes I should have made that much clearer. You can pass biocparallel arguments using the ... part of the functions. In the most recent commit on the dev branch, I added the **BPPARAM** as a formal argument to ```runEscape()``` and ```escape.matrix()``` in order to allow maximum flexibility (say you want to parallelize over one system vs multiple systems). 

> My second (unrelated) problem is with using the seurat object directly (as opposed to using the assay matrix above. If I run the below using the seurat object I get the following error:

This appears to be a Seurat version issue - see [Seurat Repo](https://github.com/satijalab/seurat/issues/6904#issue-1561977989). I'll need to track it down more and see if there is anything I can do from escape's end to fix things. 

Hope that helps and thanks again,
Nick

**Comment by ncborcherding** [comment]
@jdarmitage 

Can you give me the output of ```sessionInfo()``` so I can try to make a reproducible example of your issue?

Thanks,
Nick

**Comment by ncborcherding** [comment]
Was able to recreate issue fix is in the dev branch
